import { supabase } from './supabaseClient';

export interface ProfilePhoto {
  id: string;
  userId: string;
  storagePath: string;
  sortOrder: number;
  isPrimary: boolean;
  url: string;
}

const BUCKET = 'profile-photos';
const MAX_PHOTOS = 6;
const MAX_BYTES = 5 * 1024 * 1024;
const ALLOWED = new Set(['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']);

// Signed URLs are scoped by authenticated profile identity and storage path.
// This matters for chat because a stale/legacy avatar_path must never cause a
// URL generated for one user to be reused for another user.
const signedUrlCache = new Map<string, { url: string; expiresAt: number }>();
const pendingSignedUrls = new Map<string, Promise<string>>();

const SIGNED_URL_TTL_SECONDS = 60 * 60;
const SIGNED_URL_REFRESH_MARGIN_MS = 5 * 60 * 1000;

// Storage paths are `<ownerId>/<file>`. When the caller does not pass an
// explicit identity, scope by the owner segment so the key is never path-only.
function cacheKey(path: string, userId?: string): string {
  return `${userId || path.split('/')[0] || 'unknown'}::${path}`;
}

export async function signedUrl(path: string, userId?: string): Promise<string> {
  const key = cacheKey(path, userId);
  const cached = signedUrlCache.get(key);
  if (cached && cached.expiresAt > Date.now()) return cached.url;
  const pending = pendingSignedUrls.get(key);
  if (pending) return pending;
  const work = requestSignedUrl(path).then((url) => {
    signedUrlCache.set(key, { url, expiresAt: Date.now() + SIGNED_URL_TTL_SECONDS * 1000 - SIGNED_URL_REFRESH_MARGIN_MS });
    return url;
  });
  pendingSignedUrls.set(key, work);
  try { return await work; } finally { if (pendingSignedUrls.get(key) === work) pendingSignedUrls.delete(key); }
}

async function requestSignedUrl(path: string): Promise<string> {
  if (!supabase) throw new Error('Supabase is not configured.');
  const { data, error } = await supabase.storage.from(BUCKET).createSignedUrl(path, SIGNED_URL_TTL_SECONDS);
  if (error || !data?.signedUrl) throw new Error(error?.message || 'Could not load profile photo.');
  return data.signedUrl;
}

/**
 * Chat avatars may use the explicit identity-qualified form generated by
 * conversationRooms.ts:
 *   gayze-user-avatar:<userId>:<storage path>
 *
 * The returned URL is cached under that user's identity, while the actual
 * Storage request still receives only the storage path.
 */
export async function getProfilePhotoUrl(storagePathOrUrl: string | null | undefined): Promise<string | null> {
  if (!storagePathOrUrl || storagePathOrUrl === 'user') return null;
  if (storagePathOrUrl.startsWith('http://') || storagePathOrUrl.startsWith('https://')) return storagePathOrUrl;

  let path = storagePathOrUrl;
  let userId: string | undefined;
  const prefix = 'gayze-user-avatar:';
  if (storagePathOrUrl.startsWith(prefix)) {
    const encoded = storagePathOrUrl.slice(prefix.length);
    const separator = encoded.indexOf(':');
    if (separator > 0) {
      userId = encoded.slice(0, separator);
      path = encoded.slice(separator + 1);
    }
  }

  try { return await signedUrl(path, userId); } catch { return null; }
}

async function prepareUpload(file: File): Promise<{ file: File; contentType: string; extension: string }> {
  const type = file.type.toLowerCase();
  if (!ALLOWED.has(type)) throw new Error('Choose a JPG, PNG, WebP or iPhone photo.');
  if (file.size > MAX_BYTES) throw new Error('Profile photos must be 5 MB or smaller.');

  if (type === 'image/heic' || type === 'image/heif') {
    const bitmap = await createImageBitmap(file).catch(() => null);
    if (!bitmap) throw new Error('This iPhone photo is HEIC/HEIF and could not be converted by this browser. Please choose a JPG photo.');
    try {
      const canvas = document.createElement('canvas');
      canvas.width = bitmap.width;
      canvas.height = bitmap.height;
      const context = canvas.getContext('2d');
      if (!context) throw new Error('Could not prepare the photo.');
      context.drawImage(bitmap, 0, 0);
      const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/jpeg', 0.9));
      if (!blob) throw new Error('Could not convert the photo to JPG.');
      const converted = new File([blob], file.name.replace(/\.[^.]+$/, '') + '.jpg', { type: 'image/jpeg', lastModified: Date.now() });
      if (converted.size > MAX_BYTES) throw new Error('The converted photo is larger than 5 MB. Please choose a smaller photo.');
      return { file: converted, contentType: 'image/jpeg', extension: 'jpg' };
    } finally { bitmap.close(); }
  }

  return { file, contentType: type, extension: type === 'image/jpeg' ? 'jpg' : type.split('/')[1] || 'jpg' };
}

/**
 * Load ONLY the authenticated user's photos.
 * The previous implementation selected every row in profile_photos. That meant
 * the profile screen could take another user's primary image as its own avatar.
 */
export async function loadProfilePhotos(): Promise<ProfilePhoto[]> {
  if (!supabase) return [];
  const { data: auth, error: authError } = await supabase.auth.getUser();
  const userId = auth?.user?.id;
  if (authError || !userId) return [];

  const { data, error } = await supabase
    .from('profile_photos')
    .select('id,user_id,storage_path,sort_order,is_primary')
    .eq('user_id', userId)
    .order('sort_order', { ascending: true });

  if (error) {
    console.warn('[GAYZE] loadProfilePhotos error:', error.message);
    return [];
  }

  const photos: ProfilePhoto[] = [];
  for (const row of data ?? []) {
    try {
      const url = await signedUrl(row.storage_path, row.user_id);
      photos.push({ id: row.id, userId: row.user_id, storagePath: row.storage_path, sortOrder: row.sort_order, isPrimary: Boolean(row.is_primary), url });
    } catch {
      // If one image fails to sign, continue loading remaining photos.
    }
  }
  return photos;
}

export async function uploadProfilePhoto(file: File): Promise<ProfilePhoto[]> {
  if (!supabase) throw new Error('Supabase is not configured.');
  const prepared = await prepareUpload(file);
  const { data: auth, error: authError } = await supabase.auth.getUser();
  if (authError || !auth?.user?.id) throw new Error('Please sign in again.');
  const userId = auth.user.id;
  const existing = await loadProfilePhotos();
  if (existing.length >= MAX_PHOTOS) throw new Error('You can add up to 6 profile photos.');

  const photoId = crypto.randomUUID();
  const path = `${userId}/${photoId}.${prepared.extension}`;
  const { error: uploadError } = await supabase.storage.from(BUCKET).upload(path, prepared.file, { contentType: prepared.contentType, upsert: false, cacheControl: '3600' });
  if (uploadError) throw new Error(uploadError.message);

  const isFirst = existing.length === 0;
  const { error: insertError } = await supabase.from('profile_photos').insert({ user_id: userId, storage_path: path, sort_order: existing.length, is_primary: isFirst });
  if (insertError) {
    await supabase.storage.from(BUCKET).remove([path]);
    throw new Error(insertError.message);
  }
  if (isFirst) await supabase.from('profiles').update({ avatar_path: path }).eq('id', userId);
  return loadProfilePhotos();
}

export async function deleteProfilePhoto(photo: ProfilePhoto): Promise<ProfilePhoto[]> {
  if (!supabase) throw new Error('Supabase is not configured.');
  signedUrlCache.delete(cacheKey(photo.storagePath, photo.userId));
  const { data: auth, error: authError } = await supabase.auth.getUser();
  const userId = auth?.user?.id;
  if (authError || !userId || photo.userId !== userId) throw new Error('That photo does not belong to the signed-in account.');

  const { error } = await supabase.from('profile_photos').delete().eq('id', photo.id).eq('user_id', userId);
  if (error) throw new Error(error.message);
  await supabase.storage.from(BUCKET).remove([photo.storagePath]).catch(() => {});

  const remaining = await loadProfilePhotos();
  if (remaining.length > 0) {
    if (photo.isPrimary || !remaining.some((p) => p.isPrimary)) return setPrimaryProfilePhoto(remaining[0].id);
  } else {
    await supabase.from('profiles').update({ avatar_path: null }).eq('id', userId);
  }
  return remaining;
}

export async function setPrimaryProfilePhoto(photoId: string): Promise<ProfilePhoto[]> {
  if (!supabase) throw new Error('Supabase is not configured.');
  const { data: auth, error: authError } = await supabase.auth.getUser();
  const userId = auth?.user?.id;
  if (authError || !userId) throw new Error('Please sign in again.');

  const { data: photo, error: photoError } = await supabase.from('profile_photos').select('id,storage_path,user_id').eq('id', photoId).eq('user_id', userId).maybeSingle();
  if (photoError || !photo) throw new Error('That photo does not belong to the signed-in account.');

  const { error } = await supabase.rpc('mark_primary_profile_photo', { p_photo_id: photoId });
  if (error) {
    console.warn('[GAYZE] mark_primary_profile_photo RPC note:', error.message);
    await supabase.from('profile_photos').update({ is_primary: false }).eq('user_id', userId);
    await supabase.from('profile_photos').update({ is_primary: true }).eq('id', photoId).eq('user_id', userId);
  }

  await supabase.from('profiles').update({ avatar_path: photo.storage_path }).eq('id', userId);
  return loadProfilePhotos();
}

export async function reorderProfilePhotos(photoIds: string[]): Promise<ProfilePhoto[]> {
  if (!supabase) throw new Error('Supabase is not configured.');
  const { data: auth, error: authError } = await supabase.auth.getUser();
  const userId = auth?.user?.id;
  if (authError || !userId) throw new Error('Please sign in again.');
  const { data: owned } = await supabase.from('profile_photos').select('id').eq('user_id', userId).in('id', photoIds);
  if ((owned ?? []).length !== photoIds.length) throw new Error('One or more selected photos do not belong to the signed-in account.');

  const { error } = await supabase.rpc('reorder_profile_photos', { p_photo_ids: photoIds });
  if (error) {
    for (let i = 0; i < photoIds.length; i++) {
      await supabase.from('profile_photos').update({ sort_order: i }).eq('id', photoIds[i]).eq('user_id', userId);
    }
  }
  if (photoIds.length > 0) return setPrimaryProfilePhoto(photoIds[0]);
  return loadProfilePhotos();
}
