import { UserProfile, Pulse, Gathering, SafeHaven, SwarmRoom, EncryptedMessage, SafetyCheckin, DatingProfile } from '../types';
import { generateRandomKey, generateSafetyFingerprint, encryptPayload } from './cryptoService';

const MY_KEY = 'pk_7e3f89a1c09b62d3a950e1837b2d56a7f01e4c92b8d0e74f1c3a8e9d2a4c6e80';

export const INITIAL_USER: UserProfile = {
  publicKey: MY_KEY,
  shortKey: 'pk_7e3f...6e80',
  handle: 'julian.peer',
  displayName: 'Julian K.',
  bio: 'Architectural designer · espresso & gallery walks · advocate for digital privacy',
  avatarSeed: 'julian',
  neighborhood: 'Soho / Covent Garden',
  privacySetting: 'fuzzy_500m',
  safetyVerified: true,
  interests: ['Architecture', 'Film', 'Bouldering', 'Queer History', 'Specialty Coffee'],
  reliabilityScore: 94,
  verifiedPeersCount: 14,
  hapticsEnabled: true,
};

export const INITIAL_SAFE_HAVENS: SafeHaven[] = [
  {
    id: 'sh_1',
    name: "Gay's The Word Bookstore",
    type: 'bookstore',
    address: '66 Marchmont St, Bloomsbury',
    neighborhood: 'Bloomsbury',
    safetyScore: 9.9,
    features: ['Historic Safe Space', 'Trained Queer Staff', 'Free Water & Seating', 'Zero Commercial Pressure'],
    lat: 51.5255,
    lng: -0.1248,
    openHours: 'Mon-Sat 10:00 - 18:30',
    approxDistanceKm: 0.8,
    emergencyPhone: '+44 20 7278 7654',
    staffTrained: true,
  },
  {
    id: 'sh_2',
    name: 'Timberyard Community Cafe',
    type: 'cafe',
    address: '7 Upper St Martin’s Ln',
    neighborhood: 'Seven Dials',
    safetyScore: 9.7,
    features: ['Well-lit Public Space', 'Spacious Seating', 'Inclusive Restrooms', 'High Foot Traffic'],
    lat: 51.5126,
    lng: -0.1268,
    openHours: 'Daily 08:00 - 20:00',
    approxDistanceKm: 0.3,
    emergencyPhone: '+44 20 7836 2955',
    staffTrained: true,
  },
  {
    id: 'sh_3',
    name: 'Queer Britain Museum & Lounge',
    type: 'community_center',
    address: '2 Granary Square, King’s Cross',
    neighborhood: 'King’s Cross',
    safetyScore: 9.9,
    features: ['Dedicated Security Desk', 'Community Help Point', 'Quiet Zone', 'Accessible Facilities'],
    lat: 51.5358,
    lng: -0.1235,
    openHours: 'Wed-Sun 12:00 - 18:00',
    approxDistanceKm: 1.4,
    emergencyPhone: '+44 20 7837 0000',
    staffTrained: true,
  },
  {
    id: 'sh_4',
    name: 'The Yard Courtyard Bar',
    type: 'queer_bar',
    address: '57 Rupert St, Soho',
    neighborhood: 'Soho',
    safetyScore: 9.5,
    features: ['Ask for Angela Protocol', 'Outdoor Heated Courtyard', 'Bystander Intervention Trained', 'Open Air'],
    lat: 51.5124,
    lng: -0.1336,
    openHours: 'Daily 12:00 - 00:00',
    approxDistanceKm: 0.2,
    emergencyPhone: '+44 20 7437 2652',
    staffTrained: true,
  },
  {
    id: 'sh_5',
    name: 'Soho Poly Arts Safe Station',
    type: 'community_center',
    address: '16 Riding House St, Fitzrovia',
    neighborhood: 'Fitzrovia',
    safetyScore: 9.6,
    features: ['Safe Transit Hub', 'Phone Charging Desk', 'Queer Peer Champions'],
    lat: 51.5186,
    lng: -0.1415,
    openHours: 'Mon-Fri 09:00 - 21:00',
    approxDistanceKm: 0.6,
    emergencyPhone: '+44 20 7911 5000',
    staffTrained: true,
  }
];

export const INITIAL_PULSES: Pulse[] = [
  {
    id: 'pulse_1',
    peerId: 'peer_marcus',
    peerName: 'Marcus T.',
    peerShortKey: 'pk_4a91...38d2',
    peerAvatar: 'marcus',
    title: 'Post-work pour-over & indie bookstore browse',
    description: 'Finished client deck early. Reading at Timberyard courtyard for the next 2 hours. Looking for a quiet, low-key conversation or someone who loves cinema.',
    activityCategory: 'coffee',
    venueName: 'Timberyard Cafe (Verified Haven)',
    neighborhood: 'Seven Dials',
    approxDistanceKm: 0.3,
    jitterMeters: 280,
    lat: 51.5126,
    lng: -0.1268,
    durationHours: 2,
    createdAt: Date.now() - 25 * 60 * 1000,
    expiresAt: Date.now() + 95 * 60 * 1000,
    tags: ['Cinema', 'Design', 'Quiet'],
    safeHavenVenue: true,
  },
  {
    id: 'pulse_2',
    peerId: 'peer_ethan',
    peerName: 'Ethan V.',
    peerShortKey: 'pk_9b2e...51f4',
    peerAvatar: 'ethan',
    title: 'Bouldering partner at Substation',
    description: 'Looking for a climbing buddy around V3-V5 grade. Happy to teach if you are new! Planning on grabbing a matcha shake after.',
    activityCategory: 'active',
    venueName: 'Substation Bouldering Centre',
    neighborhood: 'Brixton / Central Link',
    approxDistanceKm: 1.1,
    jitterMeters: 450,
    lat: 51.4980,
    lng: -0.1210,
    durationHours: 3,
    createdAt: Date.now() - 40 * 60 * 1000,
    expiresAt: Date.now() + 140 * 60 * 1000,
    tags: ['Bouldering', 'Fitness', 'Social'],
    safeHavenVenue: false,
  },
  {
    id: 'pulse_3',
    peerId: 'peer_nicolas',
    peerName: 'Nicolas & Sam',
    peerShortKey: 'pk_11ce...990a',
    peerAvatar: 'nicolas',
    title: 'Sunset canal walk & dog watch',
    description: 'Walking our greyhound down Regent’s Canal towards Angel. Great evening light. Say hi or join us for a stretch!',
    activityCategory: 'walk',
    venueName: 'Granary Square & Towpath',
    neighborhood: 'King’s Cross',
    approxDistanceKm: 1.3,
    jitterMeters: 320,
    lat: 51.5350,
    lng: -0.1245,
    durationHours: 1.5,
    createdAt: Date.now() - 15 * 60 * 1000,
    expiresAt: Date.now() + 75 * 60 * 1000,
    tags: ['Dogs', 'Walking', 'Outdoors'],
    safeHavenVenue: true,
  },
  {
    id: 'pulse_4',
    peerId: 'peer_alex',
    peerName: 'Alex Mercer',
    peerShortKey: 'pk_68f0...a117',
    peerAvatar: 'alex',
    title: 'Pre-theatre drink in the heated garden',
    description: 'Have a 90-minute window before curtain at the Donmar Warehouse. Grabbing a sparkling water/cider at The Yard. Open to meeting fellow theater buffs.',
    activityCategory: 'drinks',
    venueName: 'The Yard Courtyard (Verified Haven)',
    neighborhood: 'Soho',
    approxDistanceKm: 0.2,
    jitterMeters: 190,
    lat: 51.5124,
    lng: -0.1336,
    durationHours: 1.5,
    createdAt: Date.now() - 10 * 60 * 1000,
    expiresAt: Date.now() + 80 * 60 * 1000,
    tags: ['Theatre', 'Soho', 'Casual'],
    safeHavenVenue: true,
  },
  {
    id: 'pulse_5',
    peerId: 'peer_damon',
    peerName: 'Damon K.',
    peerShortKey: 'pk_3d81...bc02',
    peerAvatar: 'damon',
    title: 'Co-working sprint on laptop @ British Library',
    description: 'Deep focus work sprint on some code/copywriting, with tea breaks in between. Looking for an accountability co-worker.',
    activityCategory: 'chill',
    venueName: 'British Library St Pancras',
    neighborhood: 'Euston / Bloomsbury',
    approxDistanceKm: 0.9,
    jitterMeters: 300,
    lat: 51.5298,
    lng: -0.1274,
    durationHours: 3,
    createdAt: Date.now() - 55 * 60 * 1000,
    expiresAt: Date.now() + 125 * 60 * 1000,
    tags: ['Co-working', 'Coding', 'Focus'],
    safeHavenVenue: true,
  }
];

export const INITIAL_GATHERINGS: Gathering[] = [
  {
    id: 'gath_1',
    hostId: 'peer_marcus',
    hostName: 'Marcus T.',
    hostShortKey: 'pk_4a91...38d2',
    hostAvatar: 'marcus',
    title: 'Queer Board Games & Strategy Night',
    description: 'Join us for a friendly, alcohol-optional board game session. We bring Catan, Wingspan, and Cascadia, but feel free to bring your favourites. Safe, welcoming environment with zero gatekeeping.',
    category: 'games',
    dateStr: 'Tonight, 19:00',
    timestamp: Date.now() + 3 * 3600 * 1000,
    locationName: "Gay's The Word Reading Room",
    address: '66 Marchmont St, Bloomsbury',
    neighborhood: 'Bloomsbury',
    isSafeHavenVenue: true,
    lat: 51.5255,
    lng: -0.1248,
    capacity: 16,
    rsvpCount: 11,
    isAttending: true,
    tags: ['Board Games', 'Alcohol-Free Friendly', 'Beginners Welcome'],
    safetyGuidelines: 'Safe Haven venue protocol. Code of conduct strictly enforced; no unconsented photo taking.',
  },
  {
    id: 'gath_2',
    hostId: 'peer_leo',
    hostName: 'Leo Vance',
    hostShortKey: 'pk_55aa...120f',
    hostAvatar: 'leo',
    title: 'Sunday Morning Trail Collective: Hampstead Heath',
    description: 'A relaxed 7km social jog/fast walk across the Heath hills followed by fresh pastries at Kenwood House. Pace is conversational (6:15 min/km or brisk walking group).',
    category: 'active',
    dateStr: 'Sunday, 09:30',
    timestamp: Date.now() + 4 * 86400 * 1000,
    locationName: 'Parliament Hill Bandstand',
    address: 'Hampstead Heath South Entrance',
    neighborhood: 'Hampstead',
    isSafeHavenVenue: false,
    lat: 51.5600,
    lng: -0.1550,
    capacity: 25,
    rsvpCount: 18,
    isAttending: false,
    tags: ['Running', 'Nature', 'Morning Coffee'],
    safetyGuidelines: 'Buddy system paired at start line. Live encrypted group beacon active throughout.',
  },
  {
    id: 'gath_3',
    hostId: 'peer_nicolas',
    hostName: 'Nicolas C.',
    hostShortKey: 'pk_11ce...990a',
    hostAvatar: 'nicolas',
    title: 'Queer Founders & Tech Privacy Salon',
    description: 'Intimate roundtable discussion on decentralized tech, local-first cryptography, and building safe queer spaces in the surveillance era. Light drinks and appetizers provided.',
    category: 'discussions',
    dateStr: 'Tomorrow, 18:30',
    timestamp: Date.now() + 26 * 3600 * 1000,
    locationName: 'Queer Britain Lounge',
    address: '2 Granary Square, King’s Cross',
    neighborhood: 'King’s Cross',
    isSafeHavenVenue: true,
    lat: 51.5358,
    lng: -0.1235,
    capacity: 20,
    rsvpCount: 15,
    isAttending: true,
    tags: ['Tech', 'Privacy', 'Founders'],
    safetyGuidelines: 'Chatham House Rule. End-to-end encrypted gathering room with no public attendee list.',
  },
  {
    id: 'gath_4',
    hostId: 'peer_dave',
    hostName: 'David R.',
    hostShortKey: 'pk_7833...901e',
    hostAvatar: 'david',
    title: 'Tate Modern Evening Gallery Walk & Terrace Chat',
    description: 'Exploring the new modern expressionism wing followed by sunset discussions over the river from the Blavatnik Building level 10 viewing terrace.',
    category: 'arts',
    dateStr: 'Friday, 18:00',
    timestamp: Date.now() + 2 * 86400 * 1000,
    locationName: 'Tate Modern Turbine Hall',
    address: 'Bankside, SE1 9TG',
    neighborhood: 'South Bank',
    isSafeHavenVenue: true,
    lat: 51.5076,
    lng: -0.0994,
    capacity: 14,
    rsvpCount: 9,
    isAttending: false,
    tags: ['Art', 'Museum', 'Walk'],
    safetyGuidelines: 'Public cultural institution. Staffed security and direct transit links.',
  }
];

export const INITIAL_ROOMS: SwarmRoom[] = [
  {
    id: 'room_marcus',
    name: 'Marcus T.',
    type: 'direct',
    peerKey: 'pk_4a91b2c4819df9001bfa9823e1104d88e04051a89c92b210a4ff984138d2ef10',
    peerName: 'Marcus T.',
    peerNeighborhood: 'Seven Dials',
    peerAvatar: 'marcus',
    safetyNumber: '39102 88419 20491 55910 11942 67184',
    swarmSecretKeyHex: 'seed_room_marcus_gayze_e2ee_99182',
    lastMessage: 'Sounds good! I am seated near the back window courtyard.',
    lastTimestamp: Date.now() - 12 * 60 * 1000,
    ephemeralTtlSeconds: 3600, // 1 hour burner
    verifiedViaQR: true,
    verifiedAt: Date.now() - 3600000,
    peerReliabilityScore: 98,
  },
  {
    id: 'room_gath_1',
    name: 'Queer Board Games Swarm',
    type: 'gathering',
    safetyNumber: '78291 00192 48194 92817 38471 29481',
    swarmSecretKeyHex: 'seed_gathering_board_games_swarm_7718',
    lastMessage: 'Marcus: Table reserved for 19:00. Bringing Catan expansion too.',
    lastTimestamp: Date.now() - 35 * 60 * 1000,
    ephemeralTtlSeconds: 0,
  },
  {
    id: 'room_alex',
    name: 'Alex Mercer',
    type: 'direct',
    peerKey: 'pk_68f0293da810e9bf9011928374a11700b91e847c20a911f938201a68f0a117ab',
    peerName: 'Alex Mercer',
    peerNeighborhood: 'Soho',
    safetyNumber: '19402 77481 92841 02938 48192 55912',
    swarmSecretKeyHex: 'seed_room_alex_theatre_e2ee_8821',
    lastMessage: 'The heated terrace has plenty of space tonight.',
    lastTimestamp: Date.now() - 90 * 60 * 1000,
    ephemeralTtlSeconds: 86400, // 24 hours
    verifiedViaQR: false,
    peerReliabilityScore: 91,
  }
];

export const INITIAL_MESSAGES: Record<string, EncryptedMessage[]> = {
  room_marcus: [
    {
      id: 'msg_1',
      roomId: 'room_marcus',
      senderKey: 'pk_4a91b2c4819df9001bfa9823e1104d88e04051a89c92b210a4ff984138d2ef10',
      senderName: 'Marcus T.',
      timestamp: Date.now() - 22 * 60 * 1000,
      cipherText: '3f8b029a...encrypted_payload',
      nonceHex: 'a910e47b91024c881029ab01',
      plainText: 'Hey Julian, saw your note! I just grabbed a table at Timberyard.',
    },
    {
      id: 'msg_2',
      roomId: 'room_marcus',
      senderKey: MY_KEY,
      senderName: 'Julian K.',
      timestamp: Date.now() - 18 * 60 * 1000,
      cipherText: '901fa4bb...encrypted_payload',
      nonceHex: 'b819203a9f0183740291ba22',
      plainText: 'Hey Marcus! Perfect, I’m wrapping up an elevation drawing and can be there in 8 minutes.',
    },
    {
      id: 'msg_3',
      roomId: 'room_marcus',
      senderKey: 'pk_4a91b2c4819df9001bfa9823e1104d88e04051a89c92b210a4ff984138d2ef10',
      senderName: 'Marcus T.',
      timestamp: Date.now() - 12 * 60 * 1000,
      cipherText: '710e2819...encrypted_payload',
      nonceHex: 'c0918237401928ab01928491',
      plainText: 'Sounds good! I am seated near the back window courtyard.',
    }
  ],
  room_gath_1: [
    {
      id: 'gmsg_1',
      roomId: 'room_gath_1',
      senderKey: 'pk_4a91b2c4819df9001bfa9823e1104d88e04051a89c92b210a4ff984138d2ef10',
      senderName: 'Marcus T.',
      timestamp: Date.now() - 4 * 3600 * 1000,
      cipherText: '9910ab...encrypted_payload',
      nonceHex: '192039485710293847561029',
      plainText: 'Welcome everyone to the encrypted room for tonight’s Queer Board Games! Reminder: venue is Gay’s The Word reading room.',
    },
    {
      id: 'gmsg_2',
      roomId: 'room_gath_1',
      senderKey: 'pk_11ce...990a',
      senderName: 'Nicolas C.',
      timestamp: Date.now() - 2 * 3600 * 1000,
      cipherText: 'a810f9...encrypted_payload',
      nonceHex: '847291029384710293847102',
      plainText: 'I’m bringing Wingspan with both European and Oceania expansions!',
    },
    {
      id: 'gmsg_3',
      roomId: 'room_gath_1',
      senderKey: 'pk_4a91b2c4819df9001bfa9823e1104d88e04051a89c92b210a4ff984138d2ef10',
      senderName: 'Marcus T.',
      timestamp: Date.now() - 35 * 60 * 1000,
      cipherText: '401928...encrypted_payload',
      nonceHex: '739102938471029384710293',
      plainText: 'Marcus: Table reserved for 19:00. Bringing Catan expansion too.',
    }
  ],
  room_alex: [
    {
      id: 'amsg_1',
      roomId: 'room_alex',
      senderKey: 'pk_68f0...a117',
      senderName: 'Alex Mercer',
      timestamp: Date.now() - 90 * 60 * 1000,
      cipherText: '339182...encrypted_payload',
      nonceHex: '581920394817263548192039',
      plainText: 'The heated terrace has plenty of space tonight.',
    }
  ]
};

export const INITIAL_SAFETY_CHECKIN: SafetyCheckin = {
  isActive: false,
  meetupPartnerName: 'Marcus T.',
  venueName: 'Timberyard Cafe',
  startedAt: 0,
  durationMinutes: 60,
  notes: 'Meeting for coffee after viewing pulse. If not checked in, ping buddy circle.',
  emergencyBuddyPings: 2,
};

export const INITIAL_DATING_PROFILES: DatingProfile[] = [
  {
    id: 'prof_marcus',
    name: 'Marcus',
    age: 32,
    photoUrl: '/src/assets/images/dating_profile_marcus_1790154961749.jpg',
    neighborhood: 'Soho',
    approxDistanceKm: 0.2,
    headline: 'Espresso fanatic, exhibition goer & cyclist',
    bio: 'Architectural photographer based in Soho. Passionate about brutalism, pour-overs at Timberyard, and exploring indie cinema. Looking for real chemistry, good conversation, and shared laughs.',
    lookingFor: 'dating',
    lookingForLabel: 'Dates & Drinks',
    heightCm: 184,
    rolePronouns: 'He / Him',
    interests: ['Specialty Coffee', 'Cycling', 'Contemporary Art', 'Cinema'],
    tribes: ['Professional', 'Athletic'],
    isOnline: true,
    lastActive: 'Active now',
    safetyVerified: true,
    peerPublicKey: 'pk_4a91b2c4819df9001bfa9823e1104d88e04051a89c92b210a4ff984138d2ef10',
    favoriteSafeHaven: 'Timberyard Community Cafe',
    isFavorited: false,
    reliabilityScore: 98,
    verifiedPeersCount: 18,
    verifiedViaQR: true,
  },
  {
    id: 'prof_liam',
    name: 'Liam',
    age: 28,
    photoUrl: '/src/assets/images/dating_profile_liam_1790154976059.jpg',
    neighborhood: 'Covent Garden',
    approxDistanceKm: 0.4,
    headline: 'Landscape designer, weekend trail runner & dog dad',
    bio: 'Designing green spaces across Central London. Big fan of weekend long runs along the canal, bouldering, and relaxed Sunday lunches. Looking for someone grounded, playful, and genuine.',
    lookingFor: 'relationship',
    lookingForLabel: 'Long-term & Romance',
    heightCm: 181,
    rolePronouns: 'He / Him',
    interests: ['Bouldering', 'Landscape Design', 'Indie Folk', 'Dogs'],
    tribes: ['Athletic', 'Outdoors'],
    isOnline: true,
    lastActive: 'Active now',
    safetyVerified: true,
    peerPublicKey: 'pk_718293a102948cba091823746591029384756102938475610293847561029384',
    favoriteSafeHaven: 'The Yard Courtyard Bar',
    isFavorited: true,
    reliabilityScore: 95,
    verifiedPeersCount: 11,
    verifiedViaQR: false,
  },
  {
    id: 'prof_mateo',
    name: 'Mateo',
    age: 30,
    photoUrl: '/src/assets/images/dating_profile_mateo_1790154989306.jpg',
    neighborhood: 'Fitzrovia',
    approxDistanceKm: 0.6,
    headline: 'Ceramics, late bookstore browsing & spicy ramen',
    bio: 'Studio potter and print collector. I spend Saturday afternoons getting lost in Gay’s The Word bookshop or hunting down the best handmade ramen in town. Up for spontaneous coffee or an evening stroll.',
    lookingFor: 'dates_coffee',
    lookingForLabel: 'Coffee & Walks',
    heightCm: 178,
    rolePronouns: 'He / They',
    interests: ['Ceramics', 'Bookstores', 'Cooking', 'Queer History'],
    tribes: ['Creative', 'Otter'],
    isOnline: false,
    lastActive: '12m ago',
    safetyVerified: true,
    peerPublicKey: 'pk_9918273645102938475610293847561029384756102938475610293847561029',
    favoriteSafeHaven: "Gay's The Word Bookstore",
    isFavorited: false,
    reliabilityScore: 93,
    verifiedPeersCount: 8,
    verifiedViaQR: false,
  },
  {
    id: 'prof_kenji',
    name: 'Kenji',
    age: 33,
    photoUrl: '/src/assets/images/dating_profile_kenji_1790155002292.jpg',
    neighborhood: 'Bloomsbury',
    approxDistanceKm: 0.9,
    headline: 'Architectural researcher, natural wine & jazz vinyl',
    bio: 'Passionate about sustainable timber design, Japanese jazz kissa culture, and honest conversations over low-intervention wine. Values respect, emotional intelligence, and mutual curiosity.',
    lookingFor: 'dating',
    lookingForLabel: 'Dates & Connection',
    heightCm: 175,
    rolePronouns: 'He / Him',
    interests: ['Architecture', 'Natural Wine', 'Jazz', 'Analog Photography'],
    tribes: ['Professional', 'Creative'],
    isOnline: true,
    lastActive: 'Active now',
    safetyVerified: true,
    peerPublicKey: 'pk_1029384756102938475610293847561029384756102938475610293847561029',
    favoriteSafeHaven: 'Queer Britain Museum & Lounge',
    isFavorited: false,
    reliabilityScore: 97,
    verifiedPeersCount: 15,
    verifiedViaQR: false,
  },
  {
    id: 'prof_soren',
    name: 'Soren',
    age: 27,
    photoUrl: '/src/assets/images/dating_profile_liam_1790154976059.jpg',
    neighborhood: 'Seven Dials',
    approxDistanceKm: 0.3,
    headline: 'Industrial designer, swimmer, modular synth nerd',
    bio: 'Nordic transplant living in Seven Dials. Swimming laps in the morning, patching modular synths at night. Always up for a mezcal negroni or checking out sound installations.',
    lookingFor: 'casual',
    lookingForLabel: 'Right Now / Casual',
    heightCm: 186,
    rolePronouns: 'He / Him',
    interests: ['Industrial Design', 'Swimming', 'Synths', 'Cocktails'],
    tribes: ['Athletic', 'Creative'],
    isOnline: true,
    lastActive: 'Active now',
    safetyVerified: true,
    peerPublicKey: 'pk_223344556677889900aabbccddeeff0011223344556677889900aabbccddeeff',
    favoriteSafeHaven: 'Timberyard Community Cafe',
    isFavorited: false,
    reliabilityScore: 91,
    verifiedPeersCount: 6,
    verifiedViaQR: false,
  },
  {
    id: 'prof_damian',
    name: 'Damián',
    age: 31,
    photoUrl: '/src/assets/images/dating_profile_marcus_1790154961749.jpg',
    neighborhood: 'King’s Cross',
    approxDistanceKm: 1.3,
    headline: 'Writer & curator, museum lover, fond of long talks',
    bio: 'Curating independent queer literary archives. Coffee in the morning, gallery openings in the evening. Looking for someone who enjoys good banter and thoughtful walks along Regent’s Canal.',
    lookingFor: 'relationship',
    lookingForLabel: 'Relationship & Dating',
    heightCm: 182,
    rolePronouns: 'He / Him',
    interests: ['Curating', 'Literature', 'Film', 'Travel'],
    tribes: ['Professional', 'Creative'],
    isOnline: false,
    lastActive: '45m ago',
    safetyVerified: true,
    peerPublicKey: 'pk_8899aabbccddeeff00112233445566778899aabbccddeeff0011223344556677',
    favoriteSafeHaven: 'Queer Britain Museum & Lounge',
    isFavorited: false,
    reliabilityScore: 96,
    verifiedPeersCount: 13,
    verifiedViaQR: false,
  },
  {
    id: 'prof_nico',
    name: 'Nico',
    age: 29,
    photoUrl: '/src/assets/images/dating_profile_mateo_1790154989306.jpg',
    neighborhood: 'Soho',
    approxDistanceKm: 0.1,
    headline: 'Graphic designer & printmaker, plant collector',
    bio: 'Working from studio spaces around Soho. You can usually find me sketching in outdoor cafes, trying new bakeries, or tending to too many monstera cuttings. Big on warm vibes and no games.',
    lookingFor: 'dates_coffee',
    lookingForLabel: 'Dates & Casual',
    heightCm: 177,
    rolePronouns: 'He / Him',
    interests: ['Printmaking', 'Houseplants', 'Typography', 'Baking'],
    tribes: ['Creative', 'Otter'],
    isOnline: true,
    lastActive: 'Active now',
    safetyVerified: true,
    peerPublicKey: 'pk_556677889900aabbccddeeff0011223344556677889900aabbccddeeff001122',
    favoriteSafeHaven: 'The Yard Courtyard Bar',
    isFavorited: false,
    reliabilityScore: 94,
    verifiedPeersCount: 9,
    verifiedViaQR: false,
  },
  {
    id: 'prof_alex',
    name: 'Alex',
    age: 26,
    photoUrl: '/src/assets/images/dating_profile_kenji_1790155002292.jpg',
    neighborhood: 'Holborn',
    approxDistanceKm: 0.7,
    headline: 'Software developer, board gamer, rooftop cinema fan',
    bio: 'Privacy advocate and distributed systems nerd by day, competitive board gamer by night. Looking to meet guys who love good food, witty humor, and low-key pub evenings.',
    lookingFor: 'friends',
    lookingForLabel: 'Dates or Friends',
    heightCm: 179,
    rolePronouns: 'He / They',
    interests: ['Board Games', 'Tech', 'Rooftop Cinema', 'Specialty Tea'],
    tribes: ['Geek', 'Casual'],
    isOnline: false,
    lastActive: '2h ago',
    safetyVerified: true,
    peerPublicKey: 'pk_68f0293da810e9bf9011928374a11700b91e847c20a911f938201a68f0a117ab',
    favoriteSafeHaven: "Gay's The Word Bookstore",
    isFavorited: false,
    reliabilityScore: 92,
    verifiedPeersCount: 7,
    verifiedViaQR: false,
  },
];
