import { supabase } from './supabaseClient';
import { IceCredentialCache } from './iceCredentials';
import { RealtimeRecovery, requireRealtimeSession } from './realtimeRecovery';
import { analytics } from './analyticsService';
import { saveCallRecord, markCallAsMissed } from './callHistoryService';
import type { RealtimeChannel } from '@supabase/supabase-js';

export type CallState =
  | 'idle'
  | 'calling'
  | 'ringing'
  | 'connecting'
  | 'connected'
  | 'declined'
  | 'missed'
  | 'ended'
  | 'failed';

export type CallType = 'audio' | 'video';

export interface IncomingCall {
  /** Unique per call attempt. Signals for other attempts on the same conversation are ignored. */
  callId?: string;
  conversationId: string;
  callerId: string;
  callerName: string;
  callType: CallType;
  timestamp: number;
  targetUserId?: string;
}

export interface CallSignalPayload {
  /** Unique per call attempt (generated by the caller). Stale or foreign attempts are dropped. */
  callId?: string;
  type:
    | 'call-request'
    | 'call-ringing'
    | 'call-accept'
    | 'call-decline'
    | 'call-end'
    | 'offer'
    | 'answer'
    | 'ice-candidate'
    | 'ice-restart-request';
  conversationId: string;
  callerId: string;
  callerName?: string;
  targetUserId?: string;
  callType?: CallType;
  sdp?: RTCSessionDescriptionInit;
  candidate?: RTCIceCandidateInit;
  timestamp: number;
}

export function getIceServers(): RTCIceServer[] {
  // VITE_* is public build output. Overrides may contain STUN URLs only;
  // Cloudflare TURN credentials always come from the authenticated function.
  const defaults = [
    { urls: 'stun:stun.cloudflare.com:3478' },
    { urls: 'stun:stun.l.google.com:19302' },
    { urls: 'stun:stun1.l.google.com:19302' },
    { urls: 'stun:stun2.l.google.com:19302' },
    { urls: 'stun:stun3.l.google.com:19302' },
  ];
  try {
    const parsed = JSON.parse(import.meta.env.VITE_ICE_SERVERS_JSON || '[]');
    if (Array.isArray(parsed)) {
      const urls = parsed.flatMap((entry) => Array.isArray(entry.urls) ? entry.urls : [entry.urls])
        .filter((url): url is string => typeof url === 'string' && /^stuns?:/.test(url));
      if (urls.length) return urls.map((url) => ({ urls: url }));
    }
  } catch { /* Never log a malformed env value which might contain a secret. */ }
  return defaults;
}

export class WebRTCCallService {
  private localStream: MediaStream | null = null;
  private remoteStream: MediaStream | null = null;
  private pc: RTCPeerConnection | null = null;
  private callChannel: RealtimeChannel | null = null;

  private state: CallState = 'idle';
  private errorMessage: string | null = null;
  private currentFacingMode: 'user' | 'environment' = 'user';
  private currentCallType: CallType = 'video';
  private activeConversationId: string | null = null;
  private activeTargetUserId: string | null = null;
  private ringingTimeoutTimer: number | null = null;
  private pendingIceCandidates: RTCIceCandidateInit[] = [];
  private resolvedIceServers: RTCIceServer[] | null = null;
  
  // Call history tracking
  private callStartTime: number | null = null;
  private callDirection: 'incoming' | 'outgoing' = 'outgoing';
  private callerNameForHistory: string | null = null;
  private targetUserNameForHistory: string | null = null;

  private credentialTimer: ReturnType<typeof setTimeout> | null = null;
  private restartTimer: ReturnType<typeof setTimeout> | null = null;
  private restartAttempts = 0;
  private offering = false;
  private caller = false;
  private localUserId = '';
  private callRecovery: RealtimeRecovery | null = null;
  private userRecovery: RealtimeRecovery | null = null;
  private callGeneration = 0;
  // Identity of the current attempt (caller-generated) and of the attempt we are ringing for.
  private callId: string | null = null;
  private incomingCallId: string | null = null;
  // User intent survives track replacement: applied to tracks acquired later and to flipped cameras.
  private audioIntent = true;
  private videoIntent = true;
  private acceptHandled = false;
  private connectDeadlineTimer: ReturnType<typeof setTimeout> | null = null;
  private transientSignals = new Set<() => void>();
  private iceCache = new IceCredentialCache(async () => {
    if (!supabase) throw new Error('Call service unavailable');
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 10_000);
    try {
      const { data, error } = await supabase.functions.invoke('webrtc-ice-servers', { body: {}, signal: controller.signal });
      if (error) throw new Error('Relay credential request failed');
      return data;
    } finally { clearTimeout(timer); }
  });

  private async loadIceServers(force = false): Promise<RTCIceServer[]> {
    const generation = this.callGeneration;
    let servers: RTCIceServer[];
    try { servers = await this.iceCache.get(force); }
    catch {
      // Preserve STUN fallback, but never cache a failed request permanently.
      servers = getIceServers();
    }
    if (generation !== this.callGeneration) throw new Error('Call ended');
    this.resolvedIceServers = servers;
    this.scheduleCredentialRefresh();
    return servers;
  }

  private scheduleCredentialRefresh() {
    if (this.credentialTimer) clearTimeout(this.credentialTimer);
    if (!this.activeConversationId) return;
    // Legacy responses without TTL are not cached; re-fetch before every
    // negotiation and revalidate every 30s while active. Known expiry refreshes
    // early. An explicit expiresAt/ttl is required for an exact expiry guarantee.
    const delay = this.iceCache.nextRefreshAt > Date.now()
      ? this.iceCache.nextRefreshAt - Date.now() : 30_000;
    this.credentialTimer = setTimeout(() => {
      this.credentialTimer = null;
      const pc = this.pc;
      void this.loadIceServers().then((servers) => {
        if (pc && pc === this.pc && pc.signalingState !== 'closed') pc.setConfiguration({ ...pc.getConfiguration(), iceServers: servers });
      }).catch(() => undefined);
    }, Math.max(1000, Math.min(delay, 2_147_000_000)));
  }

  constructor() {
    if (typeof window !== 'undefined') {
      window.addEventListener('pagehide', (event) => {
        if (!event.persisted) this.cleanup();
      });
    }
  }

  private stateListeners: Set<(state: CallState, error?: string | null) => void> = new Set();
  private streamListeners: Set<(local: MediaStream | null, remote: MediaStream | null) => void> = new Set();

  public getState(): CallState {
    return this.state;
  }

  public getErrorMessage(): string | null {
    return this.errorMessage;
  }

  public getLocalStream(): MediaStream | null {
    return this.localStream;
  }

  public getRemoteStream(): MediaStream | null {
    return this.remoteStream;
  }

  public subscribeState(listener: (state: CallState, error?: string | null) => void): () => void {
    this.stateListeners.add(listener);
    listener(this.state, this.errorMessage);
    return () => this.stateListeners.delete(listener);
  }

  public subscribeStreams(listener: (local: MediaStream | null, remote: MediaStream | null) => void): () => void {
    this.streamListeners.add(listener);
    listener(this.localStream, this.remoteStream);
    return () => this.streamListeners.delete(listener);
  }

  private setState(newState: CallState, error: string | null = null) {
    this.state = newState;
    this.errorMessage = error;
    for (const listener of this.stateListeners) {
      listener(newState, error);
    }
  }

  private notifyStreams() {
    for (const listener of this.streamListeners) {
      listener(this.localStream, this.remoteStream);
    }
  }

  /**
   * Listen for incoming call requests directed to this user
   */
  public initUserSignaling(
    userId: string,
    onIncomingCall: (call: IncomingCall) => void,
    onCallCancelled?: (conversationId: string) => void,
  ): () => void {
    if (!supabase) return () => undefined;

    this.userRecovery?.stop();
    const recovery = new RealtimeRecovery({
      client: supabase, userId, topic: `gayze-user-${userId}`, syncWhileJoining: false,
      // Private channel: Realtime RLS (migration 20261010090000) only lets the
      // target receive, and only lets a conversation member ring a peer.
      channelOptions: { config: { private: true, broadcast: { self: false } } },
      session: (signal) => requireRealtimeSession(supabase!, userId, signal),
      build: (channel, current) => channel.on('broadcast', { event: 'call-signal' }, (envelope: { payload: CallSignalPayload }) => {
        if (!current()) return;
        const signal = envelope.payload;
        if (!signal || signal.targetUserId && signal.targetUserId !== userId) return;
        if (!signal.callerId || !signal.conversationId) return;
        if (Date.now() - signal.timestamp > 45_000) return;
        if (signal.type === 'call-request') {
          const attemptId = signal.callId || `${signal.conversationId}:${signal.timestamp}`;
          // Duplicate delivery of the same attempt: nothing new to ring.
          if (this.incomingCallId === attemptId) return;
          const active = this.state === 'calling' || this.state === 'ringing' || this.state === 'connecting' || this.state === 'connected';
          // Busy (already in a call) or already ringing for a different attempt.
          if (active || this.incomingCallId) {
            void this.sendDirectSignal(signal.conversationId, {
              type: 'call-decline', callId: signal.callId, conversationId: signal.conversationId,
              callerId: userId, targetUserId: signal.callerId, timestamp: Date.now(),
            }).catch(() => undefined);
            return;
          }
          this.incomingCallId = attemptId;
          onIncomingCall({
            callId: signal.callId,
            conversationId: signal.conversationId,
            callerId: signal.callerId,
            callerName: signal.callerName || 'Gayze member',
            callType: signal.callType || 'video',
            timestamp: signal.timestamp || Date.now(),
          });
        } else if (signal.type === 'call-end' || signal.type === 'call-decline') {
          // Cancel only the attempt we are ringing for; a stale cancel must not dismiss a newer call.
          const attemptId = signal.callId || `${signal.conversationId}:${signal.timestamp}`;
          if (this.incomingCallId && this.incomingCallId !== attemptId && signal.callId) return;
          if (this.incomingCallId === attemptId || !this.incomingCallId) {
            this.incomingCallId = null;
          }
          onCallCancelled?.(signal.conversationId);
        }
      }),
      reconcile: async () => undefined,
      status: () => undefined,
    });
    this.userRecovery = recovery;
    return () => {
      recovery.stop();
      if (this.userRecovery === recovery) {
        this.userRecovery = null;
        this.incomingCallId = null;
        this.cleanup();
        this.setState('idle');
      }
    };
  }

  /**
   * Helper to send broadcast on a conversation channel
   */
  private async sendTransientSignal(topic: string, signal: CallSignalPayload): Promise<void> {
    if (!supabase) return;
    const client = supabase, generation = this.callGeneration;
    const channel = client.channel(topic, { config: { private: true, broadcast: { ack: true } } });
    let cancel = () => {};
    try {
      await new Promise<void>((resolve, reject) => {
        let sent = false, settled = false;
        const finish = (error?: Error) => {
          if (settled) return;
          settled = true; clearTimeout(timer);
          if (error) reject(error); else resolve();
        };
        const timer = setTimeout(() => finish(new Error('Call signal timed out')), 10_000);
        cancel = () => finish(new Error('Call ended'));
        this.transientSignals.add(cancel);
        channel.subscribe((status) => {
          if (settled) return;
          if (generation !== this.callGeneration) { cancel(); return; }
          if (status === 'SUBSCRIBED' && !sent) {
            sent = true;
            void channel.send({ type: 'broadcast', event: 'call-signal', payload: signal }, { timeout: 5000 })
              .then((result) => finish(result === 'ok' ? undefined : new Error('Call signal not acknowledged')))
              .catch(() => finish(new Error('Call signal failed')));
          } else if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT' || status === 'CLOSED') {
            finish(new Error('Call signalling unavailable'));
          }
        });
      });
    } finally {
      this.transientSignals.delete(cancel);
      void client.removeChannel(channel).catch(() => undefined);
    }
  }

  private async sendDirectSignal(conversationId: string, signal: CallSignalPayload): Promise<void> {
    if (this.callChannel && this.activeConversationId === conversationId && this.callChannel.state === 'joined') {
      await this.broadcastSignal(signal);
    } else {
      await this.sendTransientSignal(`gayze-call-${conversationId}`, signal);
    }
  }

  /**
   * Best-effort terminal signal to the peer. Uses the joined call channel when
   * available, otherwise a one-shot send on the same topic, so a hang-up is not
   * lost when our own signalling socket is momentarily reconnecting.
   */
  private async notifyPeerEnd(type: 'call-end' | 'call-decline', conversationId: string, callId: string | null, localId: string, peerId: string | null, ringingOnly: boolean) {
    const signal: CallSignalPayload = { type, callId: callId ?? undefined, conversationId, callerId: localId, targetUserId: peerId ?? undefined, timestamp: Date.now() };
    try {
      await this.sendDirectSignal(conversationId, signal);
    } catch (e) {
      console.warn('[GAYZE WebRTC] Peer could not be notified of call end', (e as Error).message);
    }
    if (ringingOnly && peerId) {
      void this.sendTransientSignal(`gayze-user-${peerId}`, signal).catch(() => undefined);
    }
  }

  /** Overridable in tests only. */
  static connectDeadlineMs = 45_000;

  private armConnectDeadline() {
    if (this.connectDeadlineTimer) clearTimeout(this.connectDeadlineTimer);
    // A call that has been accepted but never reaches media-connected must not
    // remain in 'connecting' indefinitely.
    this.connectDeadlineTimer = setTimeout(() => {
      this.connectDeadlineTimer = null;
      if (this.state === 'connecting' || this.state === 'calling' || this.state === 'ringing') {
        void this.endCall('failed', 'The call could not connect. Please try again.');
      }
    }, WebRTCCallService.connectDeadlineMs);
  }

  /**
   * Initiates an outgoing call
   */
  public async startCall(params: {
    conversationId: string;
    callerId: string;
    callerName: string;
    targetUserId: string;
    targetUserName: string;
    callType: CallType;
  }): Promise<void> {
    // Repeated taps / effect re-runs while a call is already in progress are no-ops.
    if (this.state === 'calling' || this.state === 'ringing' || this.state === 'connecting' || this.state === 'connected') {
      if (this.activeConversationId === params.conversationId) return;
    }
    this.cleanup();
    const generation = this.callGeneration;
    const callId = (typeof crypto !== 'undefined' && 'randomUUID' in crypto) ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
    this.callId = callId;
    this.videoIntent = params.callType === 'video';
    this.setState('calling');
    this.currentCallType = params.callType;
    this.activeConversationId = params.conversationId;
    this.activeTargetUserId = params.targetUserId;
    this.localUserId = params.callerId;
    this.callStartTime = Date.now();
    this.callDirection = 'outgoing';
    this.callerNameForHistory = params.callerName;
    this.targetUserNameForHistory = params.targetUserName;

    try {
      // Do not request microphone/camera access while the recipient is still
      // deciding whether to answer. Establish signalling first; local media is
      // acquired only after an explicit call-accept signal arrives.
      await this.loadIceServers();
      if (generation !== this.callGeneration) return;

      // Set up the signalling channel without local media tracks.
      await this.setupCallSignaling(params.conversationId, params.callerId, true);
      if (generation !== this.callGeneration) return;

      const request: CallSignalPayload = {
        type: 'call-request', callId, conversationId: params.conversationId,
        callerId: params.callerId, callerName: params.callerName,
        targetUserId: params.targetUserId, callType: params.callType, timestamp: Date.now(),
      };
      // Ring the recipient on their personal channel. The conversation channel
      // is also used in case they already have the screen open.
      void this.sendTransientSignal(`gayze-user-${params.targetUserId}`, request).catch(() => undefined);
      await this.broadcastSignal(request).catch(() => undefined);

      if (generation !== this.callGeneration) return;
      analytics.logEvent('call_started', { type: params.callType });

      // Auto-timeout if no answer within 35 seconds
      this.ringingTimeoutTimer = window.setTimeout(() => {
        if (this.state === 'calling' || this.state === 'ringing') {
          void this.endCall('missed');
        }
      }, 35000);
    } catch (err: any) {
      if (generation !== this.callGeneration) return;
      console.error('[GAYZE WebRTC] startCall failed:', err?.name || 'error');
      const message = this.parseMediaError(err);
      this.setState('failed', message);
      this.cleanup();
    }
  }

  /**
   * Accepts an incoming call
   */
  public async acceptCall(params: {
    conversationId: string;
    callerId: string;
    userId: string;
    callType: CallType;
    callerName?: string;
    callId?: string;
  }): Promise<void> {
    this.cleanup();
    const generation = this.callGeneration;
    const callId = params.callId ?? null;
    this.incomingCallId = null;
    this.callId = callId;
    this.videoIntent = params.callType === 'video';
    this.setState('connecting');
    this.currentCallType = params.callType;
    this.activeConversationId = params.conversationId;
    this.activeTargetUserId = params.callerId;
    this.localUserId = params.userId;
    this.callStartTime = Date.now();
    this.callDirection = 'incoming';
    this.callerNameForHistory = params.callerName || 'Unknown';
    this.targetUserNameForHistory = params.userId;

    try {
      // 1. Acquire local media
      await this.acquireLocalMedia(params.callType, generation);
      if (generation !== this.callGeneration) return;

      // 2. Load short-lived TURN credentials before creating the peer connection
      await this.loadIceServers();
      if (generation !== this.callGeneration) return;

      // 3. Join signaling channel
      await this.setupCallSignaling(params.conversationId, params.userId, false);
      if (generation !== this.callGeneration) return;

      // 4. Notify caller that call was accepted
      await this.broadcastSignal({
        type: 'call-accept', callId: callId ?? undefined,
        conversationId: params.conversationId,
        callerId: params.userId,
        targetUserId: params.callerId,
        callType: params.callType,
        timestamp: Date.now(),
      });
      if (generation !== this.callGeneration) return;
      this.armConnectDeadline();
      analytics.logEvent('call_started', { type: params.callType, direction: 'incoming' });
    } catch (err: any) {
      if (generation !== this.callGeneration) return;
      console.error('[GAYZE WebRTC] acceptCall failed:', err?.name || 'error');
      const message = this.parseMediaError(err);
      // Tell the caller immediately instead of leaving them ringing/connecting.
      await this.notifyPeerEnd('call-decline', params.conversationId, callId, params.userId, params.callerId, false);
      if (generation !== this.callGeneration) return;
      this.cleanup();
      this.setState('failed', message);
    }
  }

  /**
   * Declines an incoming call
   */
  public async declineCall(params: {
    conversationId: string;
    callerId: string;
    userId: string;
    callerName?: string;
    callId?: string;
  }): Promise<void> {
    const generation = this.callGeneration;
    this.incomingCallId = null;
    try { await this.sendDirectSignal(params.conversationId, {
      type: 'call-decline',
      callId: params.callId,
      conversationId: params.conversationId,
      callerId: params.userId,
      targetUserId: params.callerId,
      timestamp: Date.now(),
    }); } catch { /* Local decline must still complete while offline. */ }
    if (generation !== this.callGeneration) return;
    this.cleanup();
    this.setState('idle');
  }

  /**
   * Set up WebRTC peer connection and attach local tracks
   */
  private setupPeerConnection(conversationId: string, currentUserId: string): RTCPeerConnection {
    if (this.pc) {
      this.pc.close();
      this.pc = null;
    }

    const pc = new RTCPeerConnection({
      iceServers: this.resolvedIceServers || getIceServers(),
      iceCandidatePoolSize: 4,
    });

    // Attach local media tracks
    if (this.localStream) {
      this.localStream.getTracks().forEach((track) => {
        pc.addTrack(track, this.localStream!);
      });
    }

    // Handle remote tracks
    pc.ontrack = (event) => {
      if (this.pc !== pc) return;
      if (event.streams && event.streams[0]) {
        this.remoteStream = event.streams[0];
      } else {
        if (!this.remoteStream) {
          this.remoteStream = new MediaStream();
        }
        this.remoteStream.addTrack(event.track);
      }
      if (this.pc !== pc) return;
      this.notifyStreams();
    };

    // Handle ICE candidates
    pc.onicecandidate = (event) => {
      if (this.pc === pc && event.candidate) {
        void this.broadcastSignal({
          type: 'ice-candidate',
          callId: this.callId ?? undefined,
          conversationId,
          callerId: currentUserId,
          candidate: event.candidate.toJSON(),
          timestamp: Date.now(),
        }).catch(() => this.scheduleRestart());
      }
    };

    pc.onconnectionstatechange = () => {
      if (this.pc !== pc) return;
      if (pc.connectionState === 'connected') this.recovered();
      else if (pc.connectionState === 'disconnected' || pc.connectionState === 'failed') {
        this.setState('connecting');
        this.scheduleRestart(pc.connectionState === 'disconnected' ? 5000 : 500);
      }
    };
    pc.oniceconnectionstatechange = () => {
      if (this.pc !== pc) return;
      if (pc.iceConnectionState === 'connected' || pc.iceConnectionState === 'completed') this.recovered();
      else if (pc.iceConnectionState === 'failed') this.scheduleRestart(500);
    };

    this.pc = pc;
    return pc;
  }

  /**
   * Set up Realtime signaling channel for WebRTC negotiation
   */
  private async setupCallSignaling(conversationId: string, currentUserId: string, isCaller: boolean): Promise<void> {
    if (!supabase) throw new Error('Supabase Realtime is required for calling');
    this.callRecovery?.stop();
    this.caller = isCaller;
    this.localUserId = currentUserId;
    const pc = this.setupPeerConnection(conversationId, currentUserId);
    let firstJoin = true;
    let signalTail = Promise.resolve();
    await new Promise<void>((resolve, reject) => {
      const timeout = setTimeout(() => reject(new Error('Call signalling could not connect')), 25_000);
      this.callRecovery = new RealtimeRecovery({
        client: supabase!, userId: currentUserId, topic: `gayze-call-${conversationId}`, syncWhileJoining: false,
        channelOptions: { config: { private: true, broadcast: { self: false, ack: true } } },
        session: (signal) => requireRealtimeSession(supabase!, currentUserId, signal),
        build: (channel, current) => {
          this.callChannel = channel;
          return channel.on('broadcast', { event: 'call-signal' }, (envelope: { payload: CallSignalPayload }) => {
            if (!current() || this.pc !== pc) return;
            const signal = envelope.payload;
            if (!signal || signal.conversationId !== conversationId || signal.callerId === currentUserId) return;
            // Attempt identity: packets from an earlier or later attempt on this
            // conversation are stale and must never touch this peer connection.
            if (signal.callId && this.callId && signal.callId !== this.callId) return;
            // Only the authenticated peer may drive this negotiation (defence in depth
            // on top of the Realtime RLS policies).
            if (signal.callerId !== this.activeTargetUserId) return;
            signalTail = signalTail.then(async () => {
              if (current() && this.pc === pc) await this.handleCallSignal(pc, signal);
            }).catch(() => { if (current() && this.pc === pc) this.scheduleRestart(); });
          });
        },
        reconcile: async () => {
          if (this.pc !== pc) return;
          clearTimeout(timeout);
          if (firstJoin) { firstJoin = false; resolve(); }
          else if (pc.remoteDescription) this.scheduleRestart(250);
          else if (!isCaller) {
            await this.broadcastSignal({ type: 'call-accept', callId: this.callId ?? undefined, conversationId, callerId: currentUserId, targetUserId: this.activeTargetUserId ?? undefined, timestamp: Date.now() });
          }
        },
        status: (state) => {
          if (this.pc !== pc) return;
          if (state === 'sign-in-required') { clearTimeout(timeout); reject(new Error('Sign in required for calling')); this.cleanup(); this.setState('failed', 'Sign in again to call.'); }
          else if (!firstJoin && state !== 'connected') this.setState('connecting');
        },
      });
    });
  }

  private async handleCallSignal(pc: RTCPeerConnection, signal: CallSignalPayload) {
    if (this.pc !== pc) return;
    switch (signal.type) {
      case 'call-ringing':
        if (this.state === 'calling') this.setState('ringing');
        break;
      case 'call-accept':
        // Duplicate accepts (retransmits, reconnect re-announcements) are idempotent.
        if (this.caller && !this.acceptHandled) {
          this.acceptHandled = true;
          if (this.ringingTimeoutTimer) clearTimeout(this.ringingTimeoutTimer);
          this.ringingTimeoutTimer = null;
          this.setState('connecting');
          this.armConnectDeadline();

          // A caller must not capture audio/video while the recipient is still
          // being rung. Acquire media only after their explicit acceptance.
          if (!this.localStream) {
            const generation = this.callGeneration;
            try {
              await this.acquireLocalMedia(this.currentCallType, generation);
            } catch (err: any) {
              if (this.pc !== pc || generation !== this.callGeneration) return;
              // Permission denied / no device: fail visibly and tell the callee.
              console.warn('[GAYZE WebRTC] Local media unavailable:', err?.name || 'error');
              await this.endCall('failed', this.parseMediaError(err));
              return;
            }
            if (this.pc !== pc || generation !== this.callGeneration) return;
          }

          // The peer connection was created for signalling before acceptance,
          // so attach the newly-authorised tracks now, exactly once.
          if (this.localStream) {
            const attachedTrackIds = new Set(
              pc.getSenders().map((sender) => sender.track?.id).filter(Boolean),
            );
            this.localStream.getTracks().forEach((track) => {
              if (!attachedTrackIds.has(track.id)) pc.addTrack(track, this.localStream!);
            });
          }

          if (!pc.remoteDescription) await this.sendOffer(false);
        }
        break;
      case 'ice-restart-request':
        if (this.caller) this.scheduleRestart(250);
        break;
      case 'offer':
        if (!this.caller && signal.sdp) {
          // A retransmitted offer we have already answered: resend the same answer
          // rather than renegotiating (idempotent under duplicate delivery).
          if (pc.remoteDescription?.sdp === signal.sdp.sdp && pc.localDescription?.type === 'answer') {
            await this.broadcastSignal({ type: 'answer', callId: this.callId ?? undefined, conversationId: signal.conversationId, callerId: this.localUserId, sdp: pc.localDescription, timestamp: Date.now() });
            break;
          }
          this.setState('connecting');
          // Refresh our relay credentials too before answering an ICE restart.
          const servers = await this.loadIceServers();
          if (this.pc !== pc) return;
          pc.setConfiguration({ ...pc.getConfiguration(), iceServers: servers });
          await pc.setRemoteDescription(signal.sdp);
          await this.flushCandidates(pc);
          const answer = await pc.createAnswer();
          if (this.pc !== pc) return;
          await pc.setLocalDescription(answer);
          await this.broadcastSignal({ type: 'answer', callId: this.callId ?? undefined, conversationId: signal.conversationId, callerId: this.localUserId, sdp: answer, timestamp: Date.now() });
        }
        break;
      case 'answer':
        if (this.caller && signal.sdp && pc.signalingState === 'have-local-offer') {
          await pc.setRemoteDescription(signal.sdp);
          await this.flushCandidates(pc);
        }
        break;
      case 'ice-candidate':
        if (signal.candidate) {
          if (this.candidateMatches(pc, signal.candidate)) {
            // A stale or already-superseded candidate is harmless; it must not
            // trigger an ICE restart. Only a failed connection state does.
            try { await pc.addIceCandidate(signal.candidate); }
            catch { console.debug('[GAYZE WebRTC] Ignored a stale ICE candidate'); }
          } else {
            this.pendingIceCandidates = [...this.pendingIceCandidates, signal.candidate].slice(-128);
          }
        }
        break;
      case 'call-decline':
        this.cleanup(); this.setState('declined'); break;
      case 'call-end':
        this.cleanup(); this.setState('ended'); break;
    }
  }

  private candidateMatches(pc: RTCPeerConnection, candidate: RTCIceCandidateInit) {
    return Boolean(pc.remoteDescription && (!candidate.usernameFragment || pc.remoteDescription.sdp?.includes(`a=ice-ufrag:${candidate.usernameFragment}`)));
  }
  private async flushCandidates(pc: RTCPeerConnection) {
    const ready = this.pendingIceCandidates.filter((candidate) => this.candidateMatches(pc, candidate));
    this.pendingIceCandidates = this.pendingIceCandidates.filter((candidate) => !ready.includes(candidate));
    for (const candidate of ready) { if (this.pc === pc) await pc.addIceCandidate(candidate); }
  }
  private recovered() {
    this.restartAttempts = 0;
    if (this.connectDeadlineTimer) clearTimeout(this.connectDeadlineTimer);
    this.connectDeadlineTimer = null;
    if (this.restartTimer) clearTimeout(this.restartTimer);
    this.restartTimer = null;
    this.setState('connected');
  }
  private scheduleRestart(delay = 1000) {
    if (!this.pc || this.restartTimer) return;
    this.restartTimer = setTimeout(() => { this.restartTimer = null; void this.restartCallIce(); }, delay);
  }
  private async restartCallIce() {
    const pc = this.pc;
    if (!pc || !this.activeConversationId) return;
    if (this.callChannel?.state !== 'joined' || (typeof navigator !== 'undefined' && !navigator.onLine)) {
      // Recovery of the existing Supabase signalling channel owns this wait.
      this.scheduleRestart(3000);
      return;
    }
    if (++this.restartAttempts > 3) { this.cleanup(); this.setState('failed', 'The call could not reconnect. Please call again.'); return; }
    this.setState('connecting');
    try {
      if (this.caller) await this.sendOffer(true);
      else await this.broadcastSignal({ type: 'ice-restart-request', callId: this.callId ?? undefined, conversationId: this.activeConversationId, callerId: this.localUserId, timestamp: Date.now() });
    } catch { /* Bounded retry below; no credentials/SDP logged. */ }
    if (pc === this.pc) this.scheduleRestart(12_000);
  }
  private async sendOffer(restart: boolean) {
    const pc = this.pc;
    const conversationId = this.activeConversationId;
    if (!pc || !conversationId || this.offering || !this.caller) return;
    this.offering = true;
    try {
      const servers = await this.loadIceServers(restart);
      if (this.pc !== pc) return;
      pc.setConfiguration({ ...pc.getConfiguration(), iceServers: servers });
      if (pc.signalingState === 'have-local-offer' && restart) await pc.setLocalDescription({ type: 'rollback' });
      if (pc.signalingState !== 'stable') return;
      // createOffer({iceRestart:true}) performs the restart AND gives us the SDP
      // to deliver. A bare restartIce() without renegotiation cannot do that.
      const offer = await pc.createOffer({ iceRestart: restart });
      if (this.pc !== pc) return;
      await pc.setLocalDescription(offer);
      await this.broadcastSignal({ type: 'offer', callId: this.callId ?? undefined, conversationId, callerId: this.localUserId, sdp: offer, timestamp: Date.now() });
      if (!restart) this.scheduleRestart(12_000); // lost initial SDP/answer also recovers
    } finally { if (this.pc === pc) this.offering = false; }
  }
  private async broadcastSignal(signal: CallSignalPayload): Promise<void> {
    if (!this.callChannel || this.callChannel.state !== 'joined') throw new Error('Call signalling reconnecting');
    const result = await this.callChannel.send({ type: 'broadcast', event: 'call-signal', payload: signal }, { timeout: 5000 });
    if (result !== 'ok') throw new Error('Call signal was not acknowledged');
  }

  /**
   * Acquire camera and microphone media streams
   */
  private async acquireLocalMedia(callType: CallType, generation = this.callGeneration): Promise<MediaStream> {
    if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
      throw new Error('Your browser or device does not support real-time audio/video calls.');
    }

    const constraints: MediaStreamConstraints = {
      audio: {
        echoCancellation: true,
        noiseSuppression: true,
        autoGainControl: true,
      },
      video:
        callType === 'video'
          ? {
              facingMode: this.currentFacingMode,
              width: { ideal: 1280, max: 1920 },
              height: { ideal: 720, max: 1080 },
            }
          : false,
    };

    const stream = await navigator.mediaDevices.getUserMedia(constraints);
    if (generation !== this.callGeneration) { stream.getTracks().forEach((track) => track.stop()); throw new Error('Call ended'); }
    // Apply the user's mute/camera choice to the real tracks before any media flows.
    stream.getAudioTracks().forEach((track) => { track.enabled = this.audioIntent; });
    stream.getVideoTracks().forEach((track) => { track.enabled = this.videoIntent; });
    this.localStream = stream;
    this.notifyStreams();
    return stream;
  }

  /**
   * Audio mute/unmute. Changes the real microphone track (track.enabled) and
   * remembers the choice for tracks acquired later. Returns the resulting
   * enabled state so the UI can mirror the media, not its own guess.
   */
  public toggleAudio(forceEnabled?: boolean): boolean {
    const next = forceEnabled !== undefined ? forceEnabled : !this.audioIntent;
    this.audioIntent = next;
    this.localStream?.getAudioTracks().forEach((track) => { track.enabled = next; });
    return next;
  }

  /**
   * Camera on/off. Toggles the real video track; audio calls have no camera.
   */
  public toggleVideo(forceEnabled?: boolean): boolean {
    if (this.currentCallType !== 'video') return false;
    const next = forceEnabled !== undefined ? forceEnabled : !this.videoIntent;
    this.videoIntent = next;
    this.localStream?.getVideoTracks().forEach((track) => { track.enabled = next; });
    return next;
  }

  public isAudioEnabled(): boolean { return this.audioIntent; }
  public isVideoEnabled(): boolean { return this.currentCallType === 'video' && this.videoIntent; }

  /**
   * Flip between front and rear cameras on mobile
   */
  public async flipCamera(): Promise<void> {
    if (this.currentCallType !== 'video' || !this.localStream) return;

    const nextMode = this.currentFacingMode === 'user' ? 'environment' : 'user';
    try {
      const newStream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: nextMode },
      });
      const newVideoTrack = newStream.getVideoTracks()[0];
      if (!newVideoTrack) return;

      const oldTrack = this.localStream.getVideoTracks()[0];
      if (oldTrack) {
        oldTrack.stop();
        this.localStream.removeTrack(oldTrack);
      }

      newVideoTrack.enabled = this.videoIntent;
      this.localStream.addTrack(newVideoTrack);
      this.currentFacingMode = nextMode;

      // Replace track on peer connection
      if (this.pc) {
        const senders = this.pc.getSenders();
        const videoSender = senders.find((s) => s.track?.kind === 'video');
        if (videoSender) {
          await videoSender.replaceTrack(newVideoTrack);
        }
      }

      this.notifyStreams();
    } catch (err) {
      console.warn('[GAYZE WebRTC] Camera flip not supported or denied', err);
    }
  }

  /**
   * End the call and cleanly stop all tracks and close connections.
   * The peer is always told (connected, ringing or connecting), via the joined
   * channel or a one-shot send, so neither side is left active after hang-up.
   */
  public async endCall(explicitState: CallState = 'ended', message: string | null = null): Promise<void> {
    const generation = this.callGeneration, localId = this.localUserId;
    const conversationId = this.activeConversationId;
    const targetUserId = this.activeTargetUserId;
    const callId = this.callId;
    const wasRinging = this.state === 'calling' || this.state === 'ringing';
    // Notify whenever a signalling channel or a live call state exists.
    const hadPeer = Boolean(this.callChannel) || wasRinging || this.state === 'connecting' || this.state === 'connected';

    if (conversationId && hadPeer) {
      await this.notifyPeerEnd('call-end', conversationId, callId, localId, targetUserId, wasRinging);
    }
    if (generation !== this.callGeneration) return;

    // Save call record to history
    const callEndTime = Date.now();
    const durationSeconds = this.callStartTime ? Math.floor((callEndTime - this.callStartTime) / 1000) : 0;
    const isMissed = explicitState === 'missed' || explicitState === 'declined' || (wasRinging && explicitState === 'ended');
    
    if (conversationId && localId && this.callStartTime) {
      const callRecord = {
        conversationId,
        callerId: localId,
        callerName: this.callerNameForHistory || 'Unknown',
        targetUserId: targetUserId || '',
        targetUserName: this.targetUserNameForHistory || 'Unknown',
        callType: this.currentCallType,
        state: explicitState,
        startedAt: this.callStartTime,
        endedAt: callEndTime,
        durationSeconds: durationSeconds > 0 ? durationSeconds : undefined,
        direction: this.callDirection,
        isMissed,
        isRead: !isMissed, // Auto-mark as read if not missed
      };
      
      // Save call record in background
      void saveCallRecord(callRecord).catch(() => {
        console.warn('[GAYZE WebRTC] Failed to save call record');
      });
    }

    this.cleanup();
    this.setState(explicitState, message);
    // The next call starts with the microphone and camera on.
    this.audioIntent = true;

    // Reset call tracking for next call
    this.callStartTime = null;
    this.callerNameForHistory = null;
    this.targetUserNameForHistory = null;

    analytics.logEvent('call_completed', { outcome: explicitState });
  }

  /**
   * Complete teardown of all media and network resources
   */
  public cleanup() {
    ++this.callGeneration;
    this.transientSignals.forEach((cancel) => cancel());
    this.transientSignals.clear();
    this.iceCache.clear();
    this.resolvedIceServers = null;
    if (this.credentialTimer) clearTimeout(this.credentialTimer);
    if (this.restartTimer) clearTimeout(this.restartTimer);
    if (this.connectDeadlineTimer) clearTimeout(this.connectDeadlineTimer);
    this.credentialTimer = null;
    this.restartTimer = null;
    this.connectDeadlineTimer = null;
    this.restartAttempts = 0;
    this.offering = false;
    this.acceptHandled = false;
    this.callRecovery?.stop();
    this.callRecovery = null;
    this.callChannel = null;
    this.callId = null;
    this.pendingIceCandidates = [];
    this.activeTargetUserId = null;
    this.callStartTime = null;
    this.callerNameForHistory = null;
    this.targetUserNameForHistory = null;

    if (this.ringingTimeoutTimer) {
      clearTimeout(this.ringingTimeoutTimer);
      this.ringingTimeoutTimer = null;
    }

    // 1. Stop all tracks in local stream so camera/mic hardware LEDs turn off immediately
    if (this.localStream) {
      this.localStream.getTracks().forEach((track) => {
        try {
          track.stop();
        } catch (e) {
          console.warn('[GAYZE WebRTC] Track stop exception:', e);
        }
      });
      this.localStream = null;
    }

    // 2. Stop all tracks in remote stream
    if (this.remoteStream) {
      this.remoteStream.getTracks().forEach((track) => {
        try {
          track.stop();
        } catch (e) {
          console.warn('[GAYZE WebRTC] Remote track stop exception:', e);
        }
      });
      this.remoteStream = null;
    }

    // 3. Close RTCPeerConnection
    if (this.pc) {
      const pc = this.pc;
      this.pc = null;
      try {
        pc.close();
      } catch (e) {
        console.warn('[GAYZE WebRTC] PeerConnection close exception:', e);
      }
      this.pc = null;
    }

    this.activeConversationId = null;
    this.notifyStreams();
  }

  private parseMediaError(err: any): string {
    if (!err) return 'Call connection failed.';
    const name = err.name || '';
    if (name === 'NotAllowedError' || name === 'PermissionDeniedError') {
      return 'Camera or microphone permission was denied. Please allow access in browser settings.';
    }
    if (name === 'NotFoundError' || name === 'DevicesNotFoundError') {
      return 'No camera or microphone was detected on this device.';
    }
    if (name === 'NotReadableError' || name === 'TrackStartError') {
      return 'Your camera or microphone is already in use by another application.';
    }
    return err.message || 'Media connection failed.';
  }
}

export const webrtcCallService = new WebRTCCallService();
