from pathlib import Path

ROOT = Path('.')

def patch(path, old, new, label):
    p = ROOT / path
    s = p.read_text()
    if new in s:
        return
    if old not in s:
        raise SystemExit(f'MISSING {label} in {path}')
    p.write_text(s.replace(old, new, 1))

patch('src/types.ts', "  mediaType?: 'image';\n", "  mediaType?: 'image' | 'video' | 'audio';\n  scheduledFor?: number;\n  deletedForMe?: boolean;\n  deletedForEveryone?: boolean;\n  mediaDurationSeconds?: number;\n  albumId?: string;\n", 'message lifecycle types')

patch('src/App.tsx', "import { buildRoomsFromSupabase, mergeBackendRooms } from './services/conversationRooms';\n", "import { buildRoomsFromSupabase, mergeBackendRooms } from './services/conversationRooms';\nimport { deleteMessageForMe, unsendMessage, setMessageExpiry } from './services/messageLifecycleService';\n", 'lifecycle service import')

marker = "  const handleSignOut = async () => {\n"
handlers = """  const handleDeleteMessageForMe = async (messageId: string) => {\n    await deleteMessageForMe(messageId);\n    setMessages((prev) => Object.fromEntries(Object.entries(prev).map(([roomId, roomMessages]) => [\n      roomId, roomMessages.filter((message) => message.id !== messageId),\n    ])));\n  };\n\n  const handleUnsendMessage = async (messageId: string) => {\n    await unsendMessage(messageId);\n    setMessages((prev) => Object.fromEntries(Object.entries(prev).map(([roomId, roomMessages]) => [\n      roomId, roomMessages.map((message) => message.id === messageId\n        ? { ...message, deletedForEveryone: true, isBurned: false, plainText: 'Message unsent', cipherText: '' }\n        : message),\n    ])));\n  };\n\n  const handleSetMessageExpiry = async (messageId: string, ttlSeconds: number | null) => {\n    const expiresAt = ttlSeconds == null ? null : new Date(Date.now() + ttlSeconds * 1000);\n    await setMessageExpiry(messageId, expiresAt);\n    setMessages((prev) => Object.fromEntries(Object.entries(prev).map(([roomId, roomMessages]) => [\n      roomId, roomMessages.map((message) => message.id === messageId\n        ? { ...message, expiresAt: expiresAt?.getTime() }\n        : message),\n    ])));\n  };\n\n"""
patch('src/App.tsx', marker, handlers + marker, 'message lifecycle handlers')

# The ChatRoomView call is a JSX block; add props immediately after the existing delete-chat prop.
patch('src/App.tsx', "              onDeleteChat={handleDeleteChat}\n", "              onDeleteChat={handleDeleteChat}\n              onDeleteMessage={handleDeleteMessageForMe}\n              onUnsendMessage={handleUnsendMessage}\n              onSetMessageExpiry={handleSetMessageExpiry}\n", 'message lifecycle props')

patch('src/components/ChatRoomView.tsx', "import { getProfilePhotoUrl } from '../services/profilePhotoService';\n", "import { getProfilePhotoUrl } from '../services/profilePhotoService';\nimport { PhotoStudio } from './PhotoStudio';\n", 'photo studio import')
patch('src/components/ChatRoomView.tsx', "  onDeleteChat?: (roomId: string) => Promise<void>;\n", "  onDeleteChat?: (roomId: string) => Promise<void>;\n  onDeleteMessage?: (messageId: string) => Promise<void>;\n  onUnsendMessage?: (messageId: string) => Promise<void>;\n  onSetMessageExpiry?: (messageId: string, ttlSeconds: number | null) => Promise<void>;\n", 'message lifecycle props')
patch('src/components/ChatRoomView.tsx', "  onDeleteChat,\n", "  onDeleteChat,\n  onDeleteMessage,\n  onUnsendMessage,\n  onSetMessageExpiry,\n", 'message lifecycle destructuring')
patch('src/components/ChatRoomView.tsx', "  const [attachedMedia, setAttachedMedia] = useState<string | null>(null);\n", "  const [attachedMedia, setAttachedMedia] = useState<string | null>(null);\n  const [photoStudioSource, setPhotoStudioSource] = useState<string | null>(null);\n  const [messageActionId, setMessageActionId] = useState<string | null>(null);\n", 'message action state')
patch('src/components/ChatRoomView.tsx', ".filter((message) => !message.isBurned && (!message.expiresAt || message.expiresAt > now)),", ".filter((message) => !message.deletedForMe && (!message.isBurned || message.deletedForEveryone) && (!message.expiresAt || message.expiresAt > now)),", 'message filter')

bubble_old = """                  <div\n                    className={`max-w-[88%] sm:max-w-md rounded-2xl px-3.5 py-2 text-xs sm:text-sm leading-relaxed border transition-colors ${\n"""
bubble_new = """                  <div className=\"relative\">\n                  <div\n                    className={`max-w-[88%] sm:max-w-md rounded-2xl px-3.5 py-2 text-xs sm:text-sm leading-relaxed border transition-colors ${\n"""
patch('src/components/ChatRoomView.tsx', bubble_old, bubble_new, 'bubble wrapper')

patch('src/components/ChatRoomView.tsx', """                  >\n                    {/* Encrypted Photo Attachment if present */}\n""", """                  >\n                    {msg.deletedForEveryone ? (\n                      <p className=\"italic text-zinc-500\">Message unsent</p>\n                    ) : (<>\n                    {/* Encrypted Photo Attachment if present */}\n""", 'unsent rendering')
patch('src/components/ChatRoomView.tsx', """                    <div className=\"mt-1 flex items-center justify-end gap-1.5 pt-0.5 text-[11px] opacity-70\">\n""", """                    </>)}\n                    <div className=\"mt-1 flex items-center justify-end gap-1.5 pt-0.5 text-[11px] opacity-70\">\n""", 'unsent fragment close')

patch('src/components/ChatRoomView.tsx', """                    <div className=\"mt-1 flex items-center justify-end gap-1.5 pt-0.5 text-[11px] opacity-70\">\n                      <Lock className=\"w-2.5 h-2.5\" />\n""", """                    <div className=\"mt-1 flex items-center justify-end gap-1.5 pt-0.5 text-[11px] opacity-70\">\n                      {messageActionId === msg.id && (\n                        <div className=\"absolute right-0 bottom-7 z-30 w-48 rounded-xl border border-white/10 bg-[#11131a] p-1.5 shadow-2xl\">\n                          {isMe && onUnsendMessage && !msg.deletedForEveryone && (\n                            <button type=\"button\" className=\"w-full rounded-lg px-3 py-2 text-left text-[11px] text-white hover:bg-white/5\" onClick={async () => { await onUnsendMessage(msg.id); setMessageActionId(null); }}>Unsend for everyone</button>\n                          )}\n                          {onDeleteMessage && (\n                            <button type=\"button\" className=\"w-full rounded-lg px-3 py-2 text-left text-[11px] text-zinc-300 hover:bg-white/5\" onClick={async () => { await onDeleteMessage(msg.id); setMessageActionId(null); }}>Delete for me</button>\n                          )}\n                          {onSetMessageExpiry && !msg.deletedForEveryone && (\n                            <div className=\"border-t border-white/10 mt-1 pt-1\">\n                              <button type=\"button\" className=\"w-full rounded-lg px-3 py-2 text-left text-[11px] text-zinc-300 hover:bg-white/5\" onClick={async () => { await onSetMessageExpiry(msg.id, 60); setMessageActionId(null); }}>Expire in 1 minute</button>\n                              <button type=\"button\" className=\"w-full rounded-lg px-3 py-2 text-left text-[11px] text-zinc-300 hover:bg-white/5\" onClick={async () => { await onSetMessageExpiry(msg.id, 3600); setMessageActionId(null); }}>Expire in 1 hour</button>\n                              <button type=\"button\" className=\"w-full rounded-lg px-3 py-2 text-left text-[11px] text-zinc-300 hover:bg-white/5\" onClick={async () => { await onSetMessageExpiry(msg.id, null); setMessageActionId(null); }}>Never expire</button>\n                            </div>\n                          )}\n                        </div>\n                      )}\n                      <button type=\"button\" aria-label=\"Message actions\" className=\"min-w-[32px] min-h-[32px] text-zinc-500 hover:text-white\" onClick={() => setMessageActionId((value) => value === msg.id ? null : msg.id)}>•••</button>\n                      <Lock className=\"w-2.5 h-2.5\" />\n""", 'message action menu')

patch('src/components/ChatRoomView.tsx', """                <div className=\"text-[11px] pr-2\">\n                  <span className=\"text-zinc-200 font-semibold block\">Photo attached</span>\n                  <span className=\"text-emerald-400/90 text-[10.5px]\">Encrypted on send</span>\n                </div>\n""", """                <div className=\"text-[11px] pr-2\">\n                  <span className=\"text-zinc-200 font-semibold block\">Photo attached</span>\n                  <span className=\"text-emerald-400/90 text-[10.5px]\">Encrypted on send</span>\n                  <button type=\"button\" onClick={() => setPhotoStudioSource(attachedMedia)} className=\"text-[#C9A24D] text-[10px] mt-1\">Edit in Photo Studio</button>\n                </div>\n""", 'photo studio button')

patch('src/components/ChatRoomView.tsx', "      {/* Fullscreen Photo Zoom Modal */}\n", """      {photoStudioSource && (\n        <PhotoStudio source={photoStudioSource} onCancel={() => setPhotoStudioSource(null)} onDone={(edited) => { setAttachedMedia(edited); setPhotoStudioSource(null); }} />\n      )}\n\n      {/* Fullscreen Photo Zoom Modal */}\n""", 'photo studio overlay')

print('messaging lifecycle patch complete')
