/* @license SPDX-License-Identifier: Apache-2.0 */
import { DeletedRoomTracker } from './services/deletedRooms';
import { findDirectRoom, resolveLiveDirectChat, isConversationId } from './services/directChatRouting';
import type { ChatConnectionState } from './services/realtimeRecovery';
import type { MessageDelivery } from './services/chatSubscriptions';
import { watchNotificationInbox, markNotificationRead, type NotificationInbox, type InboxNotification } from './services/notificationInbox';
import { mergeMessage, mergeMessages } from './services/messageMerge';
import { ChatMessageProcessor, MessageBatcher } from './services/chatMessageProcessing';
import { beginChatTrace, clearChatTrace } from './services/chatTrace';
import { ChatHistoryOwnership } from './services/chatHistoryOwnership';
import { MessageAlerts } from './services/messageAlerts';
import React, { useState, useEffect, useRef, useCallback, Suspense, lazy } from 'react';
import { Navbar } from './components/Navbar';
import { IntentEdgeGlow } from './components/IntentEdgeGlow';
import { GayzeLoadingScreen } from './components/GayzeLoadingScreen';
import { SafetyTimerModal } from './components/SafetyTimerModal';
import { DiscreetMaskView } from './components/DiscreetMaskView';
import { IdentityModal } from './components/IdentityModal';
import { ScheduleMeetingModal } from './components/ScheduleMeetingModal';
import { EncryptedCallModal } from './components/EncryptedCallModal';
import { IncomingCallModal } from './components/IncomingCallModal';
import type { EditSectionKey } from './config/profileOptions';
import type { ProfileSavePayload } from './components/ProfileEditSheet';
import { SetIntentSheet, UserActiveIntent } from './components/SetIntentSheet';
import { AuthView, type AuthMode } from './components/AuthView';
import { ProfileOnboarding } from './components/ProfileOnboarding';
import { InstallPrompt } from './components/InstallPrompt';
import { NotificationsModal } from './components/NotificationsModal';
